// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhjygradtikonvfzarrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoanlncmFkdGlrb252ZnphcnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MTE5MjAsImV4cCI6MjA4NDA4NzkyMH0.x6TESBKDKcgHvv8U0CkoxpTRewSLWrcGxCc-uLDU4Mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});